name: qbittorrent
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Shanghai # 你的时区
      - UMASK_SET=022
      - WEBUI_PORT=8081 # 将此处修改成你欲使用的 WEB 管理平台端口 
    volumes:
      - ../../storage/qbit/config:/config # 绝对路径请修改为自己的config文件夹
      - /mnt/sdcard/downloads:/downloads # 绝对路径请修改为自己的downloads文件夹
      - /mnt/sdcard/downloads/qbit:/opt/alist/data/temp/qBittorrent  # 绝对路径请修改为自己的downloads文件夹
    ports:
      # 要使用的映射下载端口与内部下载端口，可保持默认，安装完成后在管理页面仍然可以改成其他端口。
      - "6881:6881" 
      - "6881:6881/udp"
      # 此处WEB UI 目标端口与内部端口务必保证相同，见问题1
      - "8081:8081"
    restart: unless-stopped
    # network_mode: bridge       # 网络模式选择刚才配置的桥接 bridge
    networks:
      - ipv6_bridge

networks:
  ipv6_bridge:
    external: true  # 正确位置：在顶层 networks 部分声明外部网络
