name: aria2
services:
  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    restart: unless-stopped
    environment:
      - PUID=${PUID}            # 使用当前用户的 UID
      - PGID=${PGID}            # 使用当前用户的 GID
      - UMASK_SET=022
      - RPC_SECRET=${RPC_SECRET}  # 请替换为您的实际密钥
      - RPC_PORT=${RPC_PORT}
      - LISTEN_PORT=${LISTEN_PORT}
      - DISK_CACHE=64M
      - IPV6_MODE=true         # false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=https://cf.trackerslist.com/best_aria2.txt
      - TZ=Asia/Shanghai
#    ports:
#      - "16800:6800"        # 网页端口
#      - "16888:6888"        # RPC TCP 端口
#      - "16888:6888/udp"    # RPC UDP 端口
    volumes:
      - ../../storage/aria2/config:/config
      - /mnt/sdcard/downloads:/downloads
      - /mnt/sdcard/downloads/aria2:/opt/alist/data/temp/aria2
# If you use host network mode, then no port mapping is required.
# This is the easiest way to use IPv6 networks.
    network_mode: host
#    network_mode: bridge
#    ports:
#      - 6800:6800
#      - 6888:6888
#      - 6888:6888/udp
    logging:
      driver: json-file
      options:
        max-size: 1m

# AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    command: --port 16880 --ipv6
    network_mode: host
#    network_mode: bridge
#    ports:
#      - 6880:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
