services:
  peerbanhelper:
    image: "ghostchu/peerbanhelper:latest"
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - ../../storage/PeerBanHelper/data:/app/data
    ports:
      - "9898:9898"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    network_mode: bridge       # 网络模式选择刚才配置的桥接 bridge
